name: 'mkdocs-deploy'
description: 'Build and deploy docs to GitHub Pages with MkDocs'
author: 'joshooaj'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  config:
    description: 'MkDocs config file name. Usually "mkdocs.yml". If not provided, a simple config file will be generated and used during workflow execution.'
    required: false
  site_name:
    description: 'Site name, used in header, title and drawer.'
    required: false
  site_url:
    description: 'Site url. Default value is https://owner.github.io/repository-name/. Ignored when using config.'
    required: false
  repo_name:
    description: 'Name of the MkDocs theme to use. This value is ignored when a value is provided for "config".'
    required: false
    default: ${{ github.repository }}
  docs_dir:
    description: 'Path to the root of your MkDocs site. Usually "docs/". This value is ignored when a value is provided for "config".'
    required: false
    default: 'docs/'
  remote_branch:
    description: 'Branch to use when publishing GitHub Pages site.'
    required: false
    default: 'gh-pages'
  theme:
    description: 'Name of the MkDocs theme to use. This value is ignored when a value is provided for "config".'
    required: false
    default: 'material'
  

# Define your outputs here.
outputs:
  site-name:
    description: 'MkDocs site name'
  site-url:
    description: 'MkDocs site URL'

runs:
  using: node20
  main: dist/index.js
