name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  mkdocs-build:
    name: Test mkdocs build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        config_file: ['mkdocs.yml', '']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        id: setup
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Log cache hit
        shell: bash
        run: |
          echo "python-version ${{ steps.setup.outputs.python-version }}"
          echo "cache-hit ${{ steps.setup.outputs.cache-hit }}"
      - name: Run action on ${{ matrix.os }}
        uses: ./
        with:
          config_file: ${{ matrix.config_file }}
          requirements_file: requirements.txt
          deploy: false