name: Publish to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
        - mkdocs.yml
        - requirements.yml
        - docs/**

permissions:
  contents: write
  pages: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: setup
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Publish to GitHub Pages
        uses: ./
        with:
          config_file: mkdocs.yml
          requirements_file: requirements.txt